export function createDataColumns() {
  return [
    {
      field: 'salary',
      header: {
        text: 'Salary',
        type: 'sortable',
        leadingIcon: { content: '💰', position: 'leading' },
        tooltip: { content: 'Annual Salary - Click to sort' },
        sortIndicator: { show: true, position: 'trailing' },
        interactive: true,
      },
      width: 120,
      renderer: 'number',
      sortable: true,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      field: 'years',
      header: {
        text: 'Years',
        type: 'sortable',
        leadingIcon: { content: '📅', position: 'leading' },
        tooltip: { content: 'Years of service - Click to sort' },
        sortIndicator: { show: true, position: 'trailing' },
        interactive: true,
      },
      width: 80,
      renderer: 'number',
      sortable: true,
      minWidth: 60,
    },
    {
      field: 'status',
      header: {
        text: 'Status',
        type: 'filterable',
        leadingIcon: { content: '●', position: 'leading' },
        tooltip: { content: 'Employment Status - Sortable and Filterable' },
        sortIndicator: { show: true, position: 'trailing' },
        filterIndicator: { show: true, icon: '▼', dropdownType: 'list' },
        interactive: true,
      },
      width: 100,
      renderer: 'text',
      sortable: true,
      minWidth: 80,
    },
    {
      field: 'email',
      header: {
        text: 'Email',
        type: 'sortable',
        leadingIcon: { content: '📧', position: 'leading' },
        tooltip: { content: 'Email Address - Click to sort' },
        sortIndicator: { show: true, position: 'trailing' },
        interactive: true,
      },
      width: 220,
      renderer: 'text',
      sortable: true,
      minWidth: 150,
      maxWidth: 350,
    },
    {
      field: 'phone',
      header: {
        text: 'Phone',
        type: 'text',
        leadingIcon: { content: '📱', position: 'leading' },
        tooltip: { content: 'Phone Number' },
      },
      width: 140,
      renderer: 'text',
      sortable: true,
      minWidth: 100,
    },
    {
      field: 'score',
      header: {
        text: 'Score',
        type: 'sortable',
        leadingIcon: { content: '⭐', position: 'leading' },
        tooltip: { content: 'Performance Score (1-100) - Click to sort' },
        sortIndicator: { show: true, position: 'trailing' },
        interactive: true,
      },
      width: 80,
      renderer: 'number',
      sortable: true,
      minWidth: 60,
    },
    {
      field: 'notes',
      header: {
        text: 'Notes',
        type: 'text',
        leadingIcon: { content: '📝', position: 'leading' },
        tooltip: { content: 'Additional Notes' },
      },
      width: 300,
      renderer: 'text',
      sortable: true,
      minWidth: 150,
      maxWidth: 500,
    },
  ];
}
